settings:
  react:
    version: 'detect'
env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides: [
  {
    files: ['*.ts', '*.tsx'],
    extends: [
        'plugin:@typescript-eslint/recommended',
        'plugin:@typescript-eslint/recommended-requiring-type-checking'
      ],
      parserOptions: {
        project: ['./tsconfig.json']
      },
    },
]
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  '@typescript-eslint/explicit-function-return-type': off,
  'react/react-in-jsx-scope': off,
  semi: ['error', 'always'],
  '@typescript-eslint/semi': off,
  '@typescript-eslint/no-misused-promises': [2, {
    'checksVoidReturn': {
      'attributes': false
    }
  }],
  '@typescript-eslint/no-floating-promises': off
}
ignorePatterns: [
  'vite-env.d.ts',
  'vite.config.ts'
]
